export const CheckoutButton = 'CheckoutButton'
export const basketItemDescription = 'basketItemDescription'
export const dateBadgeTextDay = 'dateBadgeTextDay'
export const dateBadgeTextMonth = 'dateBadgeTextMonth'
export const basketTotalPrice = 'basketTotalPrice'
export const defaultPrice = 'defaultPrice'
export const basketItemLabelBrand = 'basketItemLabelBrand'
export const basketItemLabelProductInfo = 'basketItemLabelProductInfo'
export const productDelete = 'delete'
export const loginPage = 'LoginFlowWrapper'
export const CloseIcon = 'CloseIcon'

// URL
export const basket = 'basket'
export const account = 'account'