export const productImage = 'productImage'
export const productImageView = 'productImageView'
export const ProductSliderFullscreen = 'ProductSliderFullscreen'
export const productSliderSliderNav = 'productSliderSliderNav'
export const productSliderBullets = 'productSliderBullets'
export const backButton_navigation = 'backButton_navigation'
export const addToBasket = 'addToBasket'
export const addToWishlist = 'addToWishlist'
export const WishListIcon = 'WishListIcon'
export const priceBox = 'priceBox'
export const finalPrice = 'finalPrice'
export const lowestProductPrice30D = 'lowestProductPrice30D'
export const brandLogoContainer = 'brandLogoContainer'
export const productColorInfoLabel = 'productColorInfoLabel'
export const productColorInfoSelectedOptionName = 'productColorInfoSelectedOptionName'
export const sizeLabel = 'sizeLabel'
export const sizeFlyoutOpener = 'sizeFlyoutOpener'
export const sizeSelector_empty = 'sizeSelector_empty'
export const sizeSelector_label = 'sizeSelector_label'
export const sizeOptionList = 'sizeOptionList'
export const addToBasketButton = 'addToBasketButton'
export const productDetailsHighlights = 'productDetailsHighlights'
export const productName = 'productName'
export const productDetailsShowMoreButton = 'productDetailsShowMoreButton'
export const UspContainer = 'UspContainer'
export const brandRecoLane = 'brandRecoLane'
export const filterFlyoutSectionHeader = 'filterFlyoutSectionHeader'
export const filterSecondaryButton = 'filterSecondaryButton'
export const filterPrimaryButton = 'filterPrimaryButton'
export const filterFlyoutSectionColor = 'filterFlyoutSectionColor'

// filter buttons
export const filterFlyoutFooterResetAll = 'filterFlyoutFooterResetAll'
export const filterFlyoutFooterSubmit = 'filterFlyoutFooterSubmit'
export const proceedToCheckoutButton = 'proceedToCheckoutButton'

// size
export const EUSize = 'tabs_tab_1'
export const EUSizeSelected = 'tabs_tab_1_selected'
export const sizeList = 'sizeList'

// Message
export const successMessage = 'Successfully added to your cart!'
export const goToBasketButton = 'goToBasketButton'
export const productDetailsLabel = 'productDetailsLabel'
export const productDetailsCloseIcon= 'productDetailsCloseIcon'
export const optionContentLabel = 'optionContentLabel'